version: '3'

services:
  app:
    image: hansleolml/spring_docker:2.0
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - 8080:3000


  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bdboot
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306




  
